services:
  # Node chính (Primary)
  mongo1:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db

  # Node phụ 1 (Secondary)
  mongo2:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db

  # Node phụ 2 (Secondary)
  mongo3:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db

  # Backend của Quan
  api:
    build: ./BE
    ports:
      - "3000:3000"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    environment:
      - MONGO_URI=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/todoX?replicaSet=rs0

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: